/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ca_juliusdavies_nanotime_Clock */

#ifndef _Included_ca_juliusdavies_nanotime_Clock
#define _Included_ca_juliusdavies_nanotime_Clock
#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: IS_WINDOWS */
/* Inaccessible static: cachedWindowsTime */
/* Inaccessible static: class_00024ca_00024juliusdavies_00024nanotime_00024Clock */
/*
 * Class:     ca_juliusdavies_nanotime_Clock
 * Method:    getTime
 * Signature: ([J)V
 */
JNIEXPORT void JNICALL Java_ca_juliusdavies_nanotime_Clock_getTime
  (JNIEnv *, jclass, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
